apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-tcp-port-router.fullname" . }}
  labels:
    {{- include "nginx-tcp-port-router.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-tcp-port-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nginx-tcp-port-router.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports: {{ range .Values.servicePorts }}
            - name: service-{{ . }}
              containerPort: {{ . }}
              protocol: TCP{{ end}}
          volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
