apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-tcp-port-router.fullname" . }}
  labels:
    {{- include "nginx-tcp-port-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ range .Values.servicePorts }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
      name: service-{{ . }}{{ end}}
  selector:
    {{- include "nginx-tcp-port-router.selectorLabels" . | nindent 4 }}
